### ISSUE TITLE
[enhancement] Agregar/Remover cotizaciones.

### ISSUE THREAD

**Issue by ann0nip** [outaTiME/ambito-dolar#1]
Hola Ariel,
Che, te estaba por decir que estaría bueno implementar la cotización del dólar USDT. Pero ahora vi que agregaste el CCB (que me parece habría que ver de ajustarlo porque no coincide con el precio de Binance p2p).
Fuera de eso, me llevó a pensar, que tal vez como **feature**, ya que en este país tenemos cada vez mas tipos de cambios; la posibilidad de que el usuario agregue/quite la cotización que desea.

Ej: A mi no me interesa saber el valor del dolar oficial, CCL ni Mep. Pero si el Solidario, Blue y CCB.

Si le das la posibilidad de esto al usuario, es mas fácil ver la información, y ademas la App no tiene que realizar llamadas a todas las APIs ya que solo va a llamar a las que el usuario necesita consumir. Es un win-win.

**Comment by outaTiME** [comment]
Buenas @ann0nip, 
tengo agendado en mi roadmap la posibilidad de customizar la visualización de la pizarra de cotizaciones, esto incluye agregado, eliminación y ordenamiento, veremos si lo puedo tener para la próxima versión.

Tema USDT de momento lo veo complicado, por ello se agregó como excepción el dólar Cripto o CCB de CriptoYa, desde sus comienzos el objetivo de este proyecto fue estar lo más alineado posible con Ámbito Financiero (por eso su nombre 😅).

**Comment by ann0nip** [comment]
Hola @outaTiME,
Me alegra saber que lo del custom board está en el roadmap 🚀

Y respecto a lo del USDT, entiendo perfectamente. BTW yo lo solventé con un [widget](https://github.com/ann0nip/widget-dolar-binance-p2p) en Scriptable que hice para iOS.


Así que nada, la mejor! Un abrazo.

**Comment by outaTiME** [comment]
@ann0nip ya es posible personalizar la pizarra de cotizaciones a partir de la versión 6.5.0 🔥
