### ISSUE TITLE
Dolar blue con mal precio

### ISSUE THREAD

**Issue by matichewer** [outaTiME/ambito-dolar#2]
Aparece el dolar blue a 26 pesos

![image](https://user-images.githubusercontent.com/48109018/186943438-137e5185-4254-44f5-9cbd-472e8a8a77d5.png)

**Comment by outaTiME** [comment]
Mati, cómo estás? 
Gracias por tu reporte, ya se encuentra solucionado, el proveedor mando cualquiera en los datos de las cotizaciones 🤦‍♂️
