### ISSUE TITLE
No recibo nuevas cotizaciones del dólar desde el 12/10 en Android

### ISSUE THREAD

**Issue by idanieri** [outaTiME/ambito-dolar#4]
Hola! Primero que nada quería agradecerte porque la app está muy buena. Algo que noté es que con la última actualización que recibí por Google Play ya no recibo más actualizaciones de las distintas cotizaciones del dolar. Esto pasa desde el 12/10 y hoy 16/10 sigue igual.

No sé si sirve el dato, mi celu es un Samsung S23. Sumo una captura de cómo veo la app en este momento:

![Screenshot_20231016_100749_mbito Dlar](https://github.com/outaTiME/ambito-dolar/assets/70342556/f7c63464-4621-44e6-aa7e-4a70a1fb46c3)

Saludos!

**Comment by outaTiME** [comment]
Hola @idanieri, 
te comento que las actualizaciones de las cotizaciones son únicamente los días donde hay operatoria cambiaria.
Las cotizaciones son mayoritariamente provistas por Ámbito Financiero, por lo tanto, son coincidentes con las de su página.
Hoy al igual que el viernes es feriado, así que mañana ya deberías tener nuevamente actualizaciones.
